### ISSUE TITLE
Alignment with key vendors

### ISSUE THREAD

**Issue by mahewitt** [equinor/api-strategy#70]
Many of the key vendors have their own extensive API style guidlines. Whilst strategy and some details might be specific for Equinor, does it make sense to align with one of these vendors as a general starting point and highlight differences rather than 'reinventing the wheel'?

http://apistylebook.com/design/guidelines/

**Comment by oyron** [comment]
Good question. 
Yes, many of the documents behind the pages in the API Stylebook are quite long and detailed. I agree that we should not reinvent the wheel. Creating very detailed guidelines like this would probably not make sense for several reasons. But I'm not sure if we can attach closely to some external guidelines due to the broad range of applications and APIs we have in Equinor. With these vendor guidelines being quite extensive - and probably created for more homogenous system landscapes - we would probably have a lot of cases where the guidelines does not work for everyone. 
But we should keep in mind that we don't reinvent the wheel when we add more API guidelines to the strategy. I think it makes sense to focus mostly on high level principles, and then refer to external document for details and further readings. The API strategy already links to the Microsoft and Zalando guidelines, which both are of great quality. And we can probably add more from the API stylebook. I've read through most of them a while ago, but they should probably revisited.

**Comment by mahewitt** [comment]
Agree with what you write @oyron.

Closing: Action - keep this in mind for future.
